//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalAccount
    {
        public string ExternalAccNum { get; set; }
        public string BankCode { get; set; }
        public string AccountHolder { get; set; }
        public Nullable<decimal> Balance { get; set; }
    
        public virtual ExternalBank ExternalBank { get; set; }
    }
}
