//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public string AccountNumber { get; set; }
        public int ProviderID { get; set; }
        public string BillCode { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual Account Account { get; set; }
    }
}
