//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanSchedule
    {
        public int ScheduleID { get; set; }
        public string ContractID { get; set; }
        public System.DateTime DueDate { get; set; }
        public decimal ExpectedPrincipal { get; set; }
        public decimal ExpectedInterest { get; set; }
        public Nullable<decimal> PrincipalPaid { get; set; }
        public Nullable<decimal> InterestPaid { get; set; }
        public Nullable<decimal> PenaltyAmount { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> PenaltyPaid { get; set; }
    
        public virtual LoanContract LoanContract { get; set; }
    }
}
