//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mock_Napas_Accounts
    {
        public int MockID { get; set; }
        public string AccountNumber { get; set; }
        public string BankCode { get; set; }
        public string FullName { get; set; }
    }
}
