//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotiID { get; set; }
        public string ReceiverAccount { get; set; }
        public string Message { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
