//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingTransaction
    {
        public int TransactionID { get; set; }
        public string ContractID { get; set; }
        public string TransactionType { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Notes { get; set; }
    
        public virtual SavingContract SavingContract { get; set; }
    }
}
